/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/aSrjOaWSxNk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Checkbox } from "@/components/ui/checkbox"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Createsession() {
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Student Enrollment Sessions</h1>
        <Button size="sm">Create Session</Button>
      </div>
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-6 mb-8">
        <h2 className="text-lg font-semibold mb-4">Create Session</h2>
        <form>
          <div className="grid grid-cols-2 gap-6">
            <div>
              <Label htmlFor="session-name">Session Name</Label>
              <Input id="session-name" placeholder="Enter session name" type="text" />
            </div>
            <div>
              <Label>Session Type</Label>
              <div className="flex items-center space-x-4">
                <Checkbox id="professional" value="professional">
                  Professional Elective
                </Checkbox>
                <Checkbox id="open-elective" value="open-elective">
                  Open Elective
                </Checkbox>
              </div>
            </div>
            <div>
              <Label htmlFor="excel-file">Excel File Upload</Label>
              <Input id="excel-file" type="file" />
            </div>
            <div className="grid grid-cols-3 gap-4">
              <div>
                <Label htmlFor="start-date">Start Date</Label>
                <Input id="start-date" type="date" />
              </div>
              <div>
                <Label htmlFor="start-time">Start Time</Label>
                <Input id="start-time" type="time" />
              </div>
              <div>
                <Label htmlFor="end-date">End Date</Label>
                <Input id="end-date" type="date" />
              </div>
              <div>
                <Label htmlFor="end-time">End Time</Label>
                <Input id="end-time" type="time" />
              </div>
            </div>
          </div>
          <div className="mt-6 flex justify-end">
            <Button type="submit">Create Session</Button>
          </div>
        </form>
      </div>
      <div>
        <h2 className="text-lg font-semibold mb-4">Sessions</h2>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Session Name</TableHead>
              <TableHead>Session Type</TableHead>
              <TableHead>Start Time</TableHead>
              <TableHead>End Time</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>Introduction to Programming</TableCell>
              <TableCell>Professional</TableCell>
              <TableCell>9:00 AM</TableCell>
              <TableCell>11:00 AM</TableCell>
              <TableCell>
                <div className="flex items-center space-x-2">
                  <Button size="sm" variant="outline">
                    Start
                  </Button>
                  <Button size="sm" variant="outline">
                    Stop
                  </Button>
                  <Button size="sm" variant="outline">
                    Details
                  </Button>
                </div>
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell>Data Structures and Algorithms</TableCell>
              <TableCell>Open Elective</TableCell>
              <TableCell>2:00 PM</TableCell>
              <TableCell>4:00 PM</TableCell>
              <TableCell>
                <div className="flex items-center space-x-2">
                  <Button size="sm" variant="outline">
                    Start
                  </Button>
                  <Button size="sm" variant="outline">
                    Stop
                  </Button>
                  <Button size="sm" variant="outline">
                    Details
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
